export const designSkills = [
  {
    id: "frontend-design",
    name: "Frontend Design",
    author: "Anthropic",
    focus: "Visual direction",
    href: "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
    title: "Give an interface a point of view.",
    description: "Guidance for intentional typography, composition, color, and distinctive frontend interfaces, shaped around a specific brief.",
    application: "Start with the feeling and the content, then make a small set of decisions about type, space, and emphasis. Compare the result in the browser before adding more decoration.",
    principle: "Same words. A clearer hierarchy.",
    hint: "Switch the hierarchy and notice what your eye finds first.",
    demo: "hierarchy",
    example: "Compare this portfolio’s visual themes",
    project: "/#lab",
  },
  {
    id: "ui-ux-pro-max",
    name: "UI UX Pro Max",
    author: "Next Level Builder",
    focus: "Design systems",
    href: "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill",
    title: "Connect the visual system to the task.",
    description: "A searchable collection of styles, palettes, font pairings, UX guidance, and recommendations for different products and technology stacks.",
    application: "Use the guidance to compare directions, then choose the patterns that fit the actual user journey. Keep color roles, component states, and the next action consistent across the flow.",
    principle: "A choice should lead somewhere.",
    hint: "Choose a view. The selection and the message stay connected.",
    demo: "flow",
    example: "Explore Joi’s menu and checkout decisions",
    project: "/missions/joi-vn",
  },
  {
    id: "impeccable",
    name: "Impeccable",
    author: "Paul Bakaus",
    focus: "Critique & refinement",
    href: "https://github.com/pbakaus/impeccable",
    title: "Refinement is a design decision, too.",
    description: "Design guidance and focused workflows for critiquing, polishing, clarifying, and strengthening an interface’s details and states.",
    application: "Review one interaction at a time: does the label explain the action, does the state confirm it, and does the feedback feel right? Refine the whole exchange rather than only the surface.",
    principle: "An action deserves an answer.",
    hint: "Save the idea, then reset it to compare both states.",
    demo: "feedback",
    example: "See the interaction work in 100b.studio",
    project: "/missions/100b-studio",
  },
  {
    id: "react-best-practices",
    name: "React Best Practices",
    author: "Vercel",
    focus: "Frontend performance",
    href: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices",
    title: "Make the experience feel ready sooner.",
    description: "React and Next.js guidance covering request waterfalls, bundle size, server and client data fetching, rendering, and unnecessary updates.",
    application: "Check what really depends on what. Start independent work together, load heavy features when needed, and measure before adding optimizations. Performance is part of how an interface feels.",
    principle: "Independent work can start together.",
    hint: "Compare the request order. This is a conceptual diagram, not a speed benchmark.",
    demo: "requests",
    example: "Explore Zuno’s app experience",
    project: "/missions/zuno",
  },
  {
    id: "web-design-guidelines",
    name: "Web Design Guidelines",
    author: "Vercel",
    focus: "Usability & accessibility",
    href: "https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines",
    title: "The small details make an interface usable.",
    description: "A UI review skill grounded in Web Interface Guidelines, including semantics, keyboard access, focus, forms, motion, and responsive behavior.",
    application: "Review the working interface with a keyboard and at narrow widths. Keep controls named, expose their state, and reveal secondary options without losing the person’s place.",
    principle: "Reveal options without losing context.",
    hint: "Try Tab and Enter to open the controls, then Tab and Space to change an option.",
    demo: "accessibility",
    example: "Explore Moza’s role-based interfaces",
    project: "/missions/moza",
  },
] as const;
